from pathlib import Path
from fastapi import HTTPException

async def getAll():
    base_dir = Path(__file__).resolve().parent
    return dict({"CaMau" : (base_dir / "../../../../Drafts/Temp Prediction/data/processed/datasets/CaMau_90.24_cleaned.csv").resolve(),
                 "DH"    : (base_dir / "../../../../Drafts/Temp Prediction/data/processed/datasets/DH_90.24_cleaned.csv").resolve(),
                 "NB"    : (base_dir / "../../../../Drafts/Temp Prediction/data/processed/datasets/NB_90.24_cleaned.csv").resolve(),
                 "QN"    : (base_dir / "../../../../Drafts/Temp Prediction/data/processed/datasets/QN_90.24_cleaned.csv").resolve(),
                 "TH"    : (base_dir / "../../../../Drafts/Temp Prediction/data/processed/datasets/TH_90.24_cleaned.csv").resolve(),
                 "TSN"   : (base_dir / "../../../../Drafts/Temp Prediction/data/processed/datasets/TSN_90.24_cleaned.csv").resolve()})
async def getModelPredict():
    base_dir = Path(__file__).resolve().parent
    return dict({"RF"  : {"CaMau" : {".csv" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/Random Forest/CaMau/train.csv").resolve(),
                                               "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/Random Forest/CaMau/valid.csv").resolve(),
                                               "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/Random Forest/CaMau/test.csv").resolve()},
                                     ".png" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/Random Forest/CaMau/train.png").resolve(),
                                               "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/Random Forest/CaMau/valid.png").resolve(),
                                               "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/Random Forest/CaMau/test.png").resolve()}},
                          "DH"    : {".csv" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/Random Forest/DH/train.csv").resolve(),
                                               "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/Random Forest/DH/valid.csv").resolve(),
                                               "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/Random Forest/DH/test.csv").resolve()},
                                     ".png" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/Random Forest/DH/train.png").resolve(),
                                               "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/Random Forest/DH/valid.png").resolve(),
                                               "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/Random Forest/DH/test.png").resolve()}},
                          "NB"    : {".csv" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/Random Forest/NB/train.csv").resolve(),
                                               "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/Random Forest/NB/valid.csv").resolve(),
                                               "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/Random Forest/NB/test.csv").resolve()},
                                     ".png" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/Random Forest/NB/train.png").resolve(),
                                               "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/Random Forest/NB/valid.png").resolve(),
                                               "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/Random Forest/NB/test.png").resolve()}},
                          "QN"    : {".csv" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/Random Forest/QN/train.csv").resolve(),
                                               "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/Random Forest/QN/valid.csv").resolve(),
                                               "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/Random Forest/QN/test.csv").resolve()},
                                     ".png" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/Random Forest/QN/train.png").resolve(),
                                               "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/Random Forest/QN/valid.png").resolve(),
                                               "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/Random Forest/QN/test.png").resolve()}},
                          "TH"     : {".csv" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/Random Forest/TH/train.csv").resolve(),
                                               "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/Random Forest/TH/valid.csv").resolve(),
                                               "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/Random Forest/TH/test.csv").resolve()},
                                     ".png" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/Random Forest/TH/train.png").resolve(),
                                               "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/Random Forest/TH/valid.png").resolve(),
                                               "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/Random Forest/TH/test.png").resolve()}},
                          "TSN"   : {".csv" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/Random Forest/TSN/train.csv").resolve(),
                                               "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/Random Forest/TSN/valid.csv").resolve(),
                                               "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/Random Forest/TSN/test.csv").resolve()},
                                     ".png" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/Random Forest/TSN/train.png").resolve(),
                                               "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/Random Forest/TSN/valid.png").resolve(),
                                               "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/Random Forest/TSN/test.png").resolve()}}},
                 "XGB"  : {"CaMau" : {".csv" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/XGBOOST/CaMau/train.csv").resolve(),
                                               "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/XGBOOST/CaMau/valid.csv").resolve(),
                                               "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/XGBOOST/CaMau/test.csv").resolve()},
                                     ".png" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/XGBOOST/CaMau/train.png").resolve(),
                                               "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/XGBOOST/CaMau/valid.png").resolve(),
                                               "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/XGBOOST/CaMau/test.png").resolve()}},
                           "DH"    : {".csv" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/XGBOOST/DH/train.csv").resolve(),
                                                "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/XGBOOST/DH/valid.csv").resolve(),
                                                "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/XGBOOST/DH/test.csv").resolve()},
                                      ".png" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/XGBOOST/DH/train.png").resolve(),
                                                "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/XGBOOST/DH/valid.png").resolve(),
                                                "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/XGBOOST/DH/test.png").resolve()}},
                           "NB"    : {".csv" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/XGBOOST/NB/train.csv").resolve(),
                                                "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/XGBOOST/NB/valid.csv").resolve(),
                                                "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/XGBOOST/NB/test.csv").resolve()},
                                      ".png" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/XGBOOST/NB/train.png").resolve(),
                                                "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/XGBOOST/NB/valid.png").resolve(),
                                                "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/XGBOOST/NB/test.png").resolve()}},
                           "QN"    : {".csv" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/XGBOOST/QN/train.csv").resolve(),
                                                "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/XGBOOST/QN/valid.csv").resolve(),
                                                "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/XGBOOST/QN/test.csv").resolve()},
                                      ".png" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/XGBOOST/QN/train.png").resolve(),
                                                "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/XGBOOST/QN/valid.png").resolve(),
                                                "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/XGBOOST/QN/test.png").resolve()}},
                           "TH"     : {".csv" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/XGBOOST/TH/train.csv").resolve(),
                                                 "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/XGBOOST/TH/valid.csv").resolve(),
                                                 "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/XGBOOST/TH/test.csv").resolve()},
                                      ".png" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/XGBOOST/TH/train.png").resolve(),
                                                "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/XGBOOST/TH/valid.png").resolve(),
                                                "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/XGBOOST/TH/test.png").resolve()}},
                           "TSN"   : {".csv" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/XGBOOST/TSN/train.csv").resolve(),
                                                "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/XGBOOST/TSN/valid.csv").resolve(),
                                                "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/XGBOOST/TSN/test.csv").resolve()},
                                      ".png" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/XGBOOST/TSN/train.png").resolve(),
                                                "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/XGBOOST/TSN/valid.png").resolve(),
                                                "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/ML/XGBOOST/TSN/test.png").resolve()}}},
                "NBEATS"  : {"CaMau" : {".csv" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/NBEATS/CaMau/train.csv").resolve(),
                                                  "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/NBEATS/CaMau/valid.csv").resolve(),
                                                  "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/NBEATS/CaMau/test.csv").resolve()},
                                        ".png" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/NBEATS/CaMau/train.png").resolve(),
                                                  "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/NBEATS/CaMau/valid.png").resolve(),
                                                  "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/NBEATS/CaMau/test.png").resolve()}},
                             "DH"    : {".csv" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/NBEATS/DH/train.csv").resolve(),
                                                  "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/NBEATS/DH/valid.csv").resolve(),
                                                  "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/NBEATS/DH/test.csv").resolve()},
                                        ".png" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/NBEATS/DH/train.png").resolve(),
                                                  "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/NBEATS/DH/valid.png").resolve(),
                                                  "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/NBEATS/DH/test.png").resolve()}},
                             "NB"    : {".csv" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/NBEATS/NB/train.csv").resolve(),
                                                  "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/NBEATS/NB/valid.csv").resolve(),
                                                  "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/NBEATS/NB/test.csv").resolve()},
                                        ".png" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/NBEATS/NB/train.png").resolve(),
                                                  "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/NBEATS/NB/valid.png").resolve(),
                                                  "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/NBEATS/NB/test.png").resolve()}},
                             "QN"    : {".csv" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/NBEATS/QN/train.csv").resolve(),
                                                  "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/NBEATS/QN/valid.csv").resolve(),
                                                  "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/NBEATS/QN/test.csv").resolve()},
                                        ".png" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/NBEATS/QN/train.png").resolve(),
                                                  "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/NBEATS/QN/valid.png").resolve(),
                                                  "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/NBEATS/QN/test.png").resolve()}},
                             "TH"     : {".csv" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/NBEATS/TH/train.csv").resolve(),
                                                   "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/NBEATS/TH/valid.csv").resolve(),
                                                   "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/NBEATS/TH/test.csv").resolve()},
                                        ".png" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/NBEATS/TH/train.png").resolve(),
                                                  "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/NBEATS/TH/valid.png").resolve(),
                                                  "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/NBEATS/TH/test.png").resolve()}},
                             "TSN"   : {".csv" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/NBEATS/TSN/train.csv").resolve(),
                                                  "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/NBEATS/TSN/valid.csv").resolve(),
                                                  "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/NBEATS/TSN/test.csv").resolve()},
                                        ".png" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/NBEATS/TSN/train.png").resolve(),
                                                  "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/NBEATS/TSN/valid.png").resolve(),
                                                  "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/NBEATS/TSN/test.png").resolve()}}},
                "TRANSFORMER"  : {"CaMau" : {".csv" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TRANSFORMER/CaMau/train.csv").resolve(),
                                                      "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TRANSFORMER/CaMau/valid.csv").resolve(),
                                                      "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TRANSFORMER/CaMau/test.csv").resolve()},
                                             ".png" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TRANSFORMER/CaMau/train.png").resolve(),
                                                       "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TRANSFORMER/CaMau/valid.png").resolve(),
                                                       "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TRANSFORMER/CaMau/test.png").resolve()}},
                                  "DH"    : {".csv" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TRANSFORMER/DH/train.csv").resolve(),
                                                       "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TRANSFORMER/DH/valid.csv").resolve(),
                                                       "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TRANSFORMER/DH/test.csv").resolve()},
                                             ".png" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TRANSFORMER/DH/train.png").resolve(),
                                                       "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TRANSFORMER/DH/valid.png").resolve(),
                                                       "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TRANSFORMER/DH/test.png").resolve()}},
                                  "NB"    : {".csv" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TRANSFORMER/NB/train.csv").resolve(),
                                                       "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TRANSFORMER/NB/valid.csv").resolve(),
                                                       "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TRANSFORMER/NB/test.csv").resolve()},
                                             ".png" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TRANSFORMER/NB/train.png").resolve(),
                                                       "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TRANSFORMER/NB/valid.png").resolve(),
                                                       "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TRANSFORMER/NB/test.png").resolve()}},
                                  "QN"    : {".csv" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TRANSFORMER/QN/train.csv").resolve(),
                                                       "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TRANSFORMER/QN/valid.csv").resolve(),
                                                       "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TRANSFORMER/QN/test.csv").resolve()},
                                             ".png" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TRANSFORMER/QN/train.png").resolve(),
                                                       "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TRANSFORMER/QN/valid.png").resolve(),
                                                       "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TRANSFORMER/QN/test.png").resolve()}},
                                  "TH"     : {".csv" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TRANSFORMER/TH/train.csv").resolve(),
                                                        "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TRANSFORMER/TH/valid.csv").resolve(),
                                                        "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TRANSFORMER/TH/test.csv").resolve()},
                                             ".png" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TRANSFORMER/TH/train.png").resolve(),
                                                       "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TRANSFORMER/TH/valid.png").resolve(),
                                                       "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TRANSFORMER/TH/test.png").resolve()}},
                                  "TSN"   : {".csv" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TRANSFORMER/TSN/train.csv").resolve(),
                                                       "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TRANSFORMER/TSN/valid.csv").resolve(),
                                                       "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TRANSFORMER/TSN/test.csv").resolve()},
                                             ".png" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TRANSFORMER/TSN/train.png").resolve(),
                                                       "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TRANSFORMER/TSN/valid.png").resolve(),
                                                       "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TRANSFORMER/TSN/test.png").resolve()}}},
                "TFT"  : {"CaMau" : {".csv" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TFT/CaMau/train.csv").resolve(),
                                               "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TFT/CaMau/valid.csv").resolve(),
                                               "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TFT/CaMau/test.csv").resolve()},
                                     ".png" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TFT/CaMau/train.png").resolve(),
                                               "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TFT/CaMau/valid.png").resolve(),
                                               "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TFT/CaMau/test.png").resolve()}},
                           "DH"    : {".csv" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TFT/DH/train.csv").resolve(),
                                                "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TFT/DH/valid.csv").resolve(),
                                                "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TFT/DH/test.csv").resolve()},
                                      ".png" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TFT/DH/train.png").resolve(),
                                                "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TFT/DH/valid.png").resolve(),
                                                "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TFT/DH/test.png").resolve()}},
                           "NB"    : {".csv" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TFT/NB/train.csv").resolve(),
                                                "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TFT/NB/valid.csv").resolve(),
                                                "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TFT/NB/test.csv").resolve()},
                                      ".png" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TFT/NB/train.png").resolve(),
                                                "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TFT/NB/valid.png").resolve(),
                                                "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TFT/NB/test.png").resolve()}},
                           "QN"    : {".csv" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TFT/QN/train.csv").resolve(),
                                                "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TFT/QN/valid.csv").resolve(),
                                                "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TFT/QN/test.csv").resolve()},
                                      ".png" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TFT/QN/train.png").resolve(),
                                                "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TFT/QN/valid.png").resolve(),
                                                "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TFT/QN/test.png").resolve()}},
                           "TH"     : {".csv" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TFT/TH/train.csv").resolve(),
                                                 "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TFT/TH/valid.csv").resolve(),
                                                 "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TFT/TH/test.csv").resolve()},
                                      ".png" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TFT/TH/train.png").resolve(),
                                                "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TFT/TH/valid.png").resolve(),
                                                "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TFT/TH/test.png").resolve()}},
                           "TSN"   : {".csv" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TFT/TSN/train.csv").resolve(),
                                                "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TFT/TSN/valid.csv").resolve(),
                                                "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TFT/TSN/test.csv").resolve()},
                                      ".png" : {"train" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TFT/TSN/train.png").resolve(),
                                                "valid" : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TFT/TSN/valid.png").resolve(),
                                                "test"  : (base_dir / "../../../../Drafts/Temp Prediction/outputs/DL/TFT/TSN/test.png").resolve()}}}})
async def findByStoreID(id):
    pass
async def findAll():
    pass


# if not data_dir.exists():
#         raise HTTPException(status_code=404, detail="Data directory not found")