from pathlib import Path
from fastapi import HTTPException

async def getAll():
    base_dir = Path(__file__).resolve().parent
    return dict({"RF" : {"model" : {"CaMau" : (base_dir / "../../../../Drafts/Temp Prediction/models/trained_models/ML/Random Forest/RF_trained_CaMau.pkl").resolve(),
                                    "DH"    : (base_dir / "../../../../Drafts/Temp Prediction/models/trained_models/ML/Random Forest/RF_trained_DH.pkl").resolve(),
                                    "QN"    : (base_dir / "../../../../Drafts/Temp Prediction/models/trained_models/ML/Random Forest/RF_trained_QN.pkl").resolve(),
                                    "TH"    : (base_dir / "../../../../Drafts/Temp Prediction/models/trained_models/ML/Random Forest/RF_trained_TH.pkl").resolve(),
                                    "TSN"   : (base_dir / "../../../../Drafts/Temp Prediction/models/trained_models/ML/Random Forest/RF_trained_TSN.pkl").resolve(),
                                    "NB"    : (base_dir / "../../../../Drafts/Temp Prediction/models/trained_models/ML/Random Forest/RF_trained_NB.pkl").resolve()},
                         "scaler" : {"CaMau" : {"x" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/ML/Random Forest/scaler_x_CaMau.pkl").resolve(),
                                                "y" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/ML/Random Forest/scaler_y_CaMau.pkl").resolve()},
                                     "DH"    : {"x" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/ML/Random Forest/scaler_x_DH.pkl").resolve(),
                                                "y" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/ML/Random Forest/scaler_y_DH.pkl").resolve()},
                                     "QN"    : {"x" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/ML/Random Forest/scaler_x_QN.pkl").resolve(),
                                                "y" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/ML/Random Forest/scaler_y_QN.pkl").resolve()},
                                     "TH"    : {"x" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/ML/Random Forest/scaler_x_TH.pkl").resolve(),
                                                "y" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/ML/Random Forest/scaler_y_TH.pkl").resolve()},
                                     "TSN"   : {"x" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/ML/Random Forest/scaler_x_TSN.pkl").resolve(),
                                                "y" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/ML/Random Forest/scaler_y_TSN.pkl").resolve()},
                                     "NB"    : {"x" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/ML/Random Forest/scaler_x_NB.pkl").resolve(),
                                                "y" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/ML/Random Forest/scaler_y_NB.pkl").resolve()}}},
                 "XGB" : {"model" : {"CaMau" : (base_dir / "../../../../Drafts/Temp Prediction/models/trained_models/ML/XGBOOST/XGB_trained_CaMau.pkl").resolve(),
                                     "DH"    : (base_dir / "../../../../Drafts/Temp Prediction/models/trained_models/ML/XGBOOST/XGB_trained_DH.pkl").resolve(),
                                     "QN"    : (base_dir / "../../../../Drafts/Temp Prediction/models/trained_models/ML/XGBOOST/XGB_trained_QN.pkl").resolve(),
                                     "TH"    : (base_dir / "../../../../Drafts/Temp Prediction/models/trained_models/ML/XGBOOST/XGB_trained_TH.pkl").resolve(),
                                     "TSN"   : (base_dir / "../../../../Drafts/Temp Prediction/models/trained_models/ML/XGBOOST/XGB_trained_TSN.pkl").resolve(),
                                     "NB"    : (base_dir / "../../../../Drafts/Temp Prediction/models/trained_models/ML/XGBOOST/XGB_trained_NB.pkl").resolve()},
                         "scaler" : {"CaMau" : {"x" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/ML/XgBoost/scaler_x_CaMau.pkl").resolve(),
                                                "y" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/ML/XgBoost/scaler_y_CaMau.pkl").resolve()},
                                     "DH"    : {"x" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/ML/XgBoost/scaler_x_DH.pkl").resolve(),
                                                "y" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/ML/XgBoost/scaler_y_DH.pkl").resolve()},
                                     "QN"    : {"x" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/ML/XgBoost/scaler_x_QN.pkl").resolve(),
                                                "y" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/ML/XgBoost/scaler_y_QN.pkl").resolve()},
                                     "TH"    : {"x" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/ML/XgBoost/scaler_x_TH.pkl").resolve(),
                                                "y" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/ML/XgBoost/scaler_y_TH.pkl").resolve()},
                                     "TSN"   : {"x" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/ML/XgBoost/scaler_x_TSN.pkl").resolve(),
                                                "y" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/ML/XgBoost/scaler_y_TSN.pkl").resolve()},
                                     "NB"    : {"x" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/ML/XgBoost/scaler_x_NB.pkl").resolve(),
                                                "y" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/ML/XgBoost/scaler_y_NB.pkl").resolve()}}},
                "NBEATS" : {"model" : {"CaMau" : (base_dir / "../../../../Drafts/Temp Prediction/models/trained_models/DL/NBEATS/NBEATS_trained_CaMau.pt").resolve(),
                                       "DH"    : (base_dir / "../../../../Drafts/Temp Prediction/models/trained_models/DL/NBEATS/NBEATS_trained_DH.pt").resolve(),
                                       "QN"    : (base_dir / "../../../../Drafts/Temp Prediction/models/trained_models/DL/NBEATS/NBEATS_trained_QN.pt").resolve(),
                                       "TH"    : (base_dir / "../../../../Drafts/Temp Prediction/models/trained_models/DL/NBEATS/NBEATS_trained_TH.pt").resolve(),
                                       "TSN"   : (base_dir / "../../../../Drafts/Temp Prediction/models/trained_models/DL/NBEATS/NBEATS_trained_TSN.pt").resolve(),
                                       "NB"    : (base_dir / "../../../../Drafts/Temp Prediction/models/trained_models/DL/NBEATS/NBEATS_trained_NB.pt").resolve()},
                           "scaler" : {"CaMau" : {"x" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/DL/NBEATS/scaler_x_CaMau.pkl").resolve(),
                                                   "y" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/DL/NBEATS/scaler_y_CaMau.pkl").resolve()},
                                       "DH"    : {"x" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/DL/NBEATS/scaler_x_DH.pkl").resolve(),
                                                   "y" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/DL/NBEATS/scaler_y_DH.pkl").resolve()},
                                       "QN"    : {"x" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/DL/NBEATS/scaler_x_QN.pkl").resolve(),
                                                   "y" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/DL/NBEATS/scaler_y_QN.pkl").resolve()},
                                       "TH"    : {"x" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/DL/NBEATS/scaler_x_TH.pkl").resolve(),
                                                   "y" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/DL/NBEATS/scaler_y_TH.pkl").resolve()},
                                       "TSN"   : {"x" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/DL/NBEATS/scaler_x_TSN.pkl").resolve(),
                                                   "y" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/DL/NBEATS/scaler_y_TSN.pkl").resolve()},
                                       "NB"    : {"x" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/DL/NBEATS/scaler_x_NB.pkl").resolve(),
                                                   "y" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/DL/NBEATS/scaler_y_NB.pkl").resolve()}},
                           "wrapper" : {"CaMau" : (base_dir / "../../../../Drafts/Temp Prediction/models/trained_models/DL/NBEATS/NBEATS_trained_wrapper_CaMau.pkl").resolve(),
                                        "DH"    : (base_dir / "../../../../Drafts/Temp Prediction/models/trained_models/DL/NBEATS/NBEATS_trained_wrapper_DH.pkl").resolve(),
                                        "QN"    : (base_dir / "../../../../Drafts/Temp Prediction/models/trained_models/DL/NBEATS/NBEATS_trained_wrapper_QN.pkl").resolve(),
                                        "TH"    : (base_dir / "../../../../Drafts/Temp Prediction/models/trained_models/DL/NBEATS/NBEATS_trained_wrapper_TH.pkl").resolve(),
                                        "TSN"   : (base_dir / "../../../../Drafts/Temp Prediction/models/trained_models/DL/NBEATS/NBEATS_trained_wrapper_TSN.pkl").resolve(),
                                        "NB"    : (base_dir / "../../../../Drafts/Temp Prediction/models/trained_models/DL/NBEATS/NBEATS_trained_wrapper_NB.pkl").resolve()}},
                "TRANSFORMER" : {"model" : {"CaMau" : (base_dir / "../../../../Drafts/Temp Prediction/models/trained_models/DL/TRANSFORMER/TRANSFORMER_trained_CaMau.pt").resolve(),
                                            "DH"    : (base_dir / "../../../../Drafts/Temp Prediction/models/trained_models/DL/TRANSFORMER/TRANSFORMER_trained_DH.pt").resolve(),
                                            "QN"    : (base_dir / "../../../../Drafts/Temp Prediction/models/trained_models/DL/TRANSFORMER/TRANSFORMER_trained_QN.pt").resolve(),
                                            "TH"    : (base_dir / "../../../../Drafts/Temp Prediction/models/trained_models/DL/TRANSFORMER/TRANSFORMER_trained_TH.pt").resolve(),
                                            "TSN"   : (base_dir / "../../../../Drafts/Temp Prediction/models/trained_models/DL/TRANSFORMER/TRANSFORMER_trained_TSN.pt").resolve(),
                                            "NB"    : (base_dir / "../../../../Drafts/Temp Prediction/models/trained_models/DL/TRANSFORMER/TRANSFORMER_trained_NB.pt").resolve()},
                                "scaler" : {"CaMau" : {"x" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/DL/TRANSFORMER/scaler_x_CaMau.pkl").resolve(),
                                                "y" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/DL/TRANSFORMER/scaler_y_CaMau.pkl").resolve()},
                                            "DH"    : {"x" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/DL/TRANSFORMER/scaler_x_DH.pkl").resolve(),
                                                    "y" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/DL/TRANSFORMER/scaler_y_DH.pkl").resolve()},
                                            "QN"    : {"x" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/DL/TRANSFORMER/scaler_x_QN.pkl").resolve(),
                                                    "y" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/DL/TRANSFORMER/scaler_y_QN.pkl").resolve()},
                                            "TH"    : {"x" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/DL/TRANSFORMER/scaler_x_TH.pkl").resolve(),
                                                    "y" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/DL/TRANSFORMER/scaler_y_TH.pkl").resolve()},
                                            "TSN"   : {"x" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/DL/TRANSFORMER/scaler_x_TSN.pkl").resolve(),
                                                    "y" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/DL/TRANSFORMER/scaler_y_TSN.pkl").resolve()},
                                            "NB"    : {"x" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/DL/TRANSFORMER/scaler_x_NB.pkl").resolve(),
                                                    "y" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/DL/TRANSFORMER/scaler_y_NB.pkl").resolve()}},
                                "wrapper" : {"CaMau" : (base_dir / "../../../../Drafts/Temp Prediction/models/trained_models/DL/TRANSFORMER/TRANSFORMER_trained_wrapper_CaMau.pkl").resolve(),
                                             "DH"    : (base_dir / "../../../../Drafts/Temp Prediction/models/trained_models/DL/TRANSFORMER/TRANSFORMER_trained_wrapper_DH.pkl").resolve(),
                                             "QN"    : (base_dir / "../../../../Drafts/Temp Prediction/models/trained_models/DL/TRANSFORMER/TRANSFORMER_trained_wrapper_QN.pkl").resolve(),
                                             "TH"    : (base_dir / "../../../../Drafts/Temp Prediction/models/trained_models/DL/TRANSFORMER/TRANSFORMER_trained_wrapper_TH.pkl").resolve(),
                                             "TSN"   : (base_dir / "../../../../Drafts/Temp Prediction/models/trained_models/DL/TRANSFORMER/TRANSFORMER_trained_wrapper_TSN.pkl").resolve(),
                                             "NB"    : (base_dir / "../../../../Drafts/Temp Prediction/models/trained_models/DL/TRANSFORMER/TRANSFORMER_trained_wrapper_NB.pkl").resolve()}},
                "TFT" : {"model" : {"CaMau" : (base_dir / "../../../../Drafts/Temp Prediction/models/trained_models/DL/TFT/TFT_trained_CaMau.pt").resolve(),
                                    "DH"    : (base_dir / "../../../../Drafts/Temp Prediction/models/trained_models/DL/TFT/TFT_trained_DH.pt").resolve(),
                                    "QN"    : (base_dir / "../../../../Drafts/Temp Prediction/models/trained_models/DL/TFT/TFT_trained_QN.pt").resolve(),
                                    "TH"    : (base_dir / "../../../../Drafts/Temp Prediction/models/trained_models/DL/TFT/TFT_trained_TH.pt").resolve(),
                                    "TSN"   : (base_dir / "../../../../Drafts/Temp Prediction/models/trained_models/DL/TFT/TFT_trained_TSN.pt").resolve(),
                                    "NB"    : (base_dir / "../../../../Drafts/Temp Prediction/models/trained_models/DL/TFT/TFT_trained_NB.pt").resolve()},
                        "scaler" : {"CaMau" : {"x" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/DL/TFT/scaler_x_CaMau.pkl").resolve(),
                                                "y" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/DL/TFT/scaler_y_CaMau.pkl").resolve()},
                                    "DH"    : {"x" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/DL/TFT/scaler_x_DH.pkl").resolve(),
                                            "y" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/DL/TFT/scaler_y_DH.pkl").resolve()},
                                    "QN"    : {"x" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/DL/TFT/scaler_x_QN.pkl").resolve(),
                                            "y" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/DL/TFT/scaler_y_QN.pkl").resolve()},
                                    "TH"    : {"x" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/DL/TFT/scaler_x_TH.pkl").resolve(),
                                            "y" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/DL/TFT/scaler_y_TH.pkl").resolve()},
                                    "TSN"   : {"x" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/DL/TFT/scaler_x_TSN.pkl").resolve(),
                                            "y" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/DL/TFT/scaler_y_TSN.pkl").resolve()},
                                    "NB"    : {"x" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/DL/TFT/scaler_x_NB.pkl").resolve(),
                                            "y" : (base_dir / "../../../../Drafts/Temp Prediction/models/checkpoints/DL/TFT/scaler_y_NB.pkl").resolve()}},
                        "wrapper" : {"CaMau" : (base_dir / "../../../../Drafts/Temp Prediction/models/trained_models/DL/TFT/TFT_trained_wrapper_CaMau.pkl").resolve(),
                                     "DH"    : (base_dir / "../../../../Drafts/Temp Prediction/models/trained_models/DL/TFT/TFT_trained_wrapper_DH.pkl").resolve(),
                                     "QN"    : (base_dir / "../../../../Drafts/Temp Prediction/models/trained_models/DL/TFT/TFT_trained_wrapper_QN.pkl").resolve(),
                                     "TH"    : (base_dir / "../../../../Drafts/Temp Prediction/models/trained_models/DL/TFT/TFT_trained_wrapper_TH.pkl").resolve(),
                                     "TSN"   : (base_dir / "../../../../Drafts/Temp Prediction/models/trained_models/DL/TFT/TFT_trained_wrapper_TSN.pkl").resolve(),
                                     "NB"    : (base_dir / "../../../../Drafts/Temp Prediction/models/trained_models/DL/TFT/TFT_trained_wrapper_NB.pkl").resolve()}}})
async def findByCountryName(name):
    pass
async def findByStoreID(id):
    pass
async def findAll():
    pass